### ISSUE TITLE
Create mod command Cog

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/ModBot#3]

**Comment by TuggyBoat** [comment]
Progress:
View Infractions: Done
ContextCommand (Message): delete and send to user thread in mod-evidence, with option to send warning DM containing message text, time sent, time removed, rule broken (with link to server rules), and reason given by moderator for deletion: Option to send DM to be added
SlashCommand: /warn: view moderator infractions, with option to send warning DM as above: Changed to warn only, moderator infractions kept to singular command, option to send DM to be added
