### ISSUE TITLE
Rules integration

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/ModBot#6]
- SlashCommand: `/rule` # - print a rule to a channel
- maintain/link-in to server rules

**Comment by TuggyBoat** [comment]
`# Global requirements:
# Guild ID, or another form of guild object
# Channel ID, or another form of channel object
# Message ID, or another form of message object
@tree.command(name='rule', description='Prints rule by rule number')
@describe(rule_number="Number of the rule you wish to print")
async def rule(interaction: discord.Interaction, rule_number: int):
    if rule_number <= 0:
        await interaction.response.send_message("Rule number must be positive.", ephemeral=True)
        return
    guild = bot.get_guild(guild_id)
    # get rule channel from guild
    rules_channel_object = guild.get_channel(rules_channel)

    # fetch rules message from rules channel
    rules_message = await rules_channel_object.fetch_message(rules_message_id)

    # get the rule embeds from the message
    rules_list = rules_message.embeds

    try:
        await interaction.response.send_message(embed=rules_list[rule_number - 1])

    except IndexError:
        await interaction.response.send_message("That rule doesn't exist!", ephemeral=True)`
       
This links solely to the rules message in the Discord

**Comment by TuggyBoat** [comment]
```python
# Global requirements:
# Guild ID, or another form of guild object
# Channel ID, or another form of channel object
# Message ID, or another form of message object
@tree.command(name='rule', description='Prints rule by rule number')
@describe(rule_number="Number of the rule you wish to print")
async def rule(interaction: discord.Interaction, rule_number: int):
    if rule_number <= 0:
        await interaction.response.send_message("Rule number must be positive.", ephemeral=True)
        return
    guild = bot.get_guild(guild_id)
    # get rule channel from guild
    rules_channel_object = guild.get_channel(rules_channel)

    # fetch rules message from rules channel
    rules_message = await rules_channel_object.fetch_message(rules_message_id)

    # get the rule embeds from the message
    rules_list = rules_message.embeds

    try:
        await interaction.response.send_message(embed=rules_list[rule_number - 1])

    except IndexError:
        await interaction.response.send_message("That rule doesn't exist!", ephemeral=True)
```
